/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // The entire app is themed through these aliases:
        //  - "white" is the *ink* of the active theme (dark text on light themes)
        //  - "black" is the *canvas* of the active theme
        // Every existing class like text-white/70, bg-white/10, border-black/20
        // therefore flips automatically when the theme changes.
        white: 'rgb(var(--fg) / <alpha-value>)',
        black: 'rgb(var(--bg) / <alpha-value>)',

        slate: {
          50: 'rgb(var(--fg) / 0.98)',
          100: 'rgb(var(--fg) / 0.94)',
          200: 'rgb(var(--fg) / 0.86)',
          300: 'rgb(var(--fg) / 0.68)',
          400: 'rgb(var(--fg-muted))',
          500: 'rgb(var(--fg-faint))',
          600: 'rgb(var(--fg-faint))',
          700: 'rgb(var(--fg-muted))',
          800: 'rgb(var(--fg))',
          900: 'rgb(var(--fg))',
        },

        emerald: {
          50: 'rgb(var(--success) / 0.08)',
          100: 'rgb(var(--success) / 0.3)',
          200: 'rgb(var(--success) / 0.85)',
          300: 'rgb(var(--success) / 0.8)',
          400: 'rgb(var(--success))',
          500: 'rgb(var(--success))',
          600: 'rgb(var(--success))',
          700: 'rgb(var(--success))',
          800: 'rgb(var(--success))',
          900: 'rgb(var(--success))',
        },
        green: {
          400: 'rgb(var(--success))',
          500: 'rgb(var(--success))',
        },
        rose: {
          50: 'rgb(var(--error) / 0.08)',
          100: 'rgb(var(--error) / 0.3)',
          200: 'rgb(var(--error) / 0.8)',
          300: 'rgb(var(--error) / 0.8)',
          400: 'rgb(var(--error))',
          500: 'rgb(var(--error))',
          600: 'rgb(var(--error))',
          700: 'rgb(var(--error))',
        },
        red: {
          50: 'rgb(var(--error) / 0.08)',
          100: 'rgb(var(--error) / 0.3)',
          200: 'rgb(var(--error) / 0.8)',
          300: 'rgb(var(--error) / 0.8)',
          400: 'rgb(var(--error))',
          500: 'rgb(var(--error))',
          600: 'rgb(var(--error))',
          700: 'rgb(var(--error))',
        },
        amber: {
          50: 'rgb(var(--warning) / 0.08)',
          100: 'rgb(var(--warning) / 0.9)',
          200: 'rgb(var(--warning) / 0.8)',
          300: 'rgb(var(--warning) / 0.8)',
          400: 'rgb(var(--warning))',
          500: 'rgb(var(--warning))',
          600: 'rgb(var(--warning))',
          700: 'rgb(var(--warning))',
        },
        sky: {
          50: 'rgb(var(--info) / 0.08)',
          100: 'rgb(var(--info) / 0.3)',
          200: 'rgb(var(--info) / 0.8)',
          300: 'rgb(var(--info) / 0.8)',
          400: 'rgb(var(--info))',
          500: 'rgb(var(--info))',
          600: 'rgb(var(--info))',
          700: 'rgb(var(--info))',
        },
        cyan: {
          50: 'rgb(var(--info) / 0.08)',
          100: 'rgb(var(--info) / 0.3)',
          200: 'rgb(var(--info) / 0.8)',
          300: 'rgb(var(--info) / 0.8)',
          400: 'rgb(var(--info))',
          500: 'rgb(var(--info))',
          600: 'rgb(var(--info))',
          700: 'rgb(var(--info))',
        },
        accent: {
          DEFAULT: 'rgb(var(--accent))',
          strong: 'rgb(var(--accent))',
          fg: 'rgb(var(--accent-fg))',
          soft: 'rgb(var(--accent) / 0.12)',
          'soft-strong': 'rgb(var(--accent) / 0.22)',
        },
        fg: {
          DEFAULT: 'rgb(var(--fg) / <alpha-value>)',
          muted: 'rgb(var(--fg-muted) / <alpha-value>)',
          faint: 'rgb(var(--fg-faint) / <alpha-value>)',
          strong: 'rgb(var(--fg) / <alpha-value>)',
        },
        plate: {
          DEFAULT: 'rgb(var(--plate) / <alpha-value>)',
          soft: 'rgb(var(--plate-soft) / <alpha-value>)',
          fg: 'rgb(var(--plate-fg) / <alpha-value>)',
          note: 'rgb(var(--plate-fg) / 0.62)',
          border: 'rgb(var(--plate-border) / <alpha-value>)',
        },
        violet: {
          100: 'rgb(var(--accent) / 0.3)',
          200: 'rgb(var(--accent) / 0.8)',
          300: 'rgb(var(--accent) / 0.8)',
          400: 'rgb(var(--accent))',
          500: 'rgb(var(--accent))',
          600: 'rgb(var(--accent))',
        },
        indigo: {
          300: 'rgb(var(--accent) / 0.8)',
          400: 'rgb(var(--accent))',
          500: 'rgb(var(--accent))',
        },
        obsidian: {
          DEFAULT: 'rgb(var(--bg))',
          50: 'rgb(var(--bg-soft))',
          100: 'rgb(var(--surface))',
          200: 'rgb(var(--surface-2))',
          300: 'rgb(var(--border))',
          400: 'rgb(var(--border-strong))',
          500: 'rgb(var(--fg-muted))',
          600: 'rgb(var(--fg-muted))',
          700: 'rgb(var(--fg-faint))',
          800: 'rgb(var(--fg-faint))',
          900: 'rgb(var(--fg))',
        },
        glass: {
          DEFAULT: 'rgb(var(--surface) / 0.6)',
          border: 'rgb(var(--border))',
          hover: 'rgb(var(--surface-2) / 0.6)',
        },
        module: {
          core: {
            DEFAULT: 'rgb(var(--fg) / 0.08)',
            border: 'rgb(var(--fg) / 0.15)',
            badge: 'rgb(var(--fg) / 0.9)',
          },
          shop: {
            DEFAULT: 'rgb(var(--fg) / 0.08)',
            border: 'rgb(var(--fg) / 0.15)',
            badge: 'rgb(var(--fg) / 0.9)',
          },
          api: {
            DEFAULT: 'rgb(var(--fg) / 0.06)',
            border: 'rgb(var(--fg) / 0.12)',
            badge: 'rgb(var(--fg) / 0.9)',
          },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      borderRadius: {
        none: '0px',
        sm: 'calc(var(--radius) * 0.25)',
        DEFAULT: 'calc(var(--radius) * 0.5)',
        md: 'calc(var(--radius) * 0.75)',
        lg: 'var(--radius)',
        xl: 'calc(var(--radius) * 1.5)',
        '2xl': 'calc(var(--radius) * 2)',
        '3xl': 'calc(var(--radius) * 2.5)',
        full: '9999px',
      },
      boxShadow: {
        'glow-sm': '0 0 10px rgb(var(--fg) / 0.10)',
        'glow-md': '0 0 20px rgb(var(--fg) / 0.12)',
        'glow-lg': '0 0 30px rgb(var(--fg) / 0.14)',
        'glow-accent': '0 0 20px rgb(var(--accent) / 0.28)',
        'accent': '0 0 18px rgb(var(--accent) / 0.35)',
        'glass': '0 8px 32px 0 rgb(0 0 0 / var(--shadow-opacity))',
        'glass-inset': 'inset 0 0 20px rgb(var(--fg) / 0.02)',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'float': 'float 3s ease-in-out infinite',
        'skeleton': 'skeleton 1.5s ease-in-out infinite',
      },
      keyframes: {
        glow: {
          '0%': { boxShadow: '0 0 10px rgb(var(--accent) / 0.2)' },
          '100%': { boxShadow: '0 0 22px rgb(var(--accent) / 0.35)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        skeleton: {
          '0%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
          '100%': { opacity: '0.4' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      fontFamily: {
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'var(--font-sans)', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
